[[redirects]]
  from = "/api/*"
  to = "http://apiirtestcashout.13.250.112.56.nip.io/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sanctum/*"
  to = "http://apiirtestcashout.13.250.112.56.nip.io/sanctum/:splat"
  status = 200
  force = true
