[[redirects]]
  from = "/api/*"
  to = "https://apiirtransaction.elevenkh.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sanctum/*"
  to = "https://apiirtransaction.elevenkh.com/sanctum/:splat"
  status = 200
  force = true
